backend:
  name: github
  repo: frivolta/filipporivolta.it-gatsby

media_folder: static/assets
public_folder: assets

collections:
  - name: portfolio
    label: Portfolio
    folder: portfolio
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: "Project Title" }
      - { name: body, label: "Descrizione", widget: markdown }
      - { name: tasks, label: "Task List", widget: markdown }
      - { name: templateKey, label: "Template"}
      - { name: "thumbnail", label: "Featured Image" }
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: title, label: "Title" }
      - { name: date, label: Date, widget: date }
      - { name: path, label: Path }
      - { name: body, label: "Descrizione", widget: markdown }




